### This notebook demonstrates the use of the pytorch 🔥 deep learning library in :
#### 1. Creating tensors, comparing and contrasting it with numpy.
#### 2. Forward propargation.
#### 3. Backpropargation.
#### 4. Calculating gradients in Pytorch.
#### 5. Creating a neural network in pytorch.

## _1. Building blocks for tensors._

In [2]:
import tensorflow_docs as docs

ModuleNotFoundError: No module named 'tensorflow_docs'

In [1]:
import torch
import numpy as np

In [2]:
#1. Creating tensors.
torch_tensor = torch.tensor([[2, 3, 5], [1, 2, 9]])
numpy_array = np.array([[2, 3, 5], [1, 2, 9]])

print(f'Pytorch tensor: {torch_tensor}')
print(f'\n Numpy array: {numpy_array}')

Pytorch tensor: tensor([[2, 3, 5],
        [1, 2, 9]])

 Numpy array: [[2 3 5]
 [1 2 9]]


In [3]:
#2. Random numbers.
torch_rand = torch.rand(2, 2)
np_random = np.random.randn(2, 2)

print(f'Pytorch random array: {torch_rand}')
print(f'\n Numpy random array: {np_random}')

Pytorch random array: tensor([[0.4823, 0.3258],
        [0.8642, 0.3672]])

 Numpy random array: [[-0.27128256 -1.10548425]
 [-0.57807964 -1.05568425]]


In [4]:
torch_rand.shape, np_random.shape

(torch.Size([2, 2]), (2, 2))

In [5]:
#3. Matrix operations.
a = torch.rand((2, 2))
b = torch.rand((2, 2))

c = torch.matmul(a, b)
print(a)
print(b)
print(f'\n {c}')

tensor([[0.7489, 0.4212],
        [0.0236, 0.2546]])
tensor([[0.4948, 0.9917],
        [0.3541, 0.6854]])

 tensor([[0.5196, 1.0313],
        [0.1018, 0.1979]])


In [6]:
a = np.random.randn(2, 2)
b = np.random.randn(2, 2)
c = np.dot(a, b)

print(a)
print(b)
print(f'\n {c}')

[[-0.93882616 -0.88145392]
 [ 0.42515251  0.73936536]]
[[ 1.54847307 -2.40016652]
 [-0.18283694 -1.28290535]]

 [[-1.29258469  3.38416106]
 [ 0.52315391 -1.96897259]]


In [7]:
#4. Zeros matrices.
a_torch = torch.zeros(2, 2)
a_numpy = np.zeros((2, 2))

print(a_torch)
print(f'\n {a_numpy}')

tensor([[0., 0.],
        [0., 0.]])

 [[0. 0.]
 [0. 0.]]


In [8]:
#5. Ones matrices.
b_torch = torch.ones(2, 2)
b_numpy = np.ones((2, 2))

print(b_torch)
print(f'\n {b_numpy}')

tensor([[1., 1.],
        [1., 1.]])

 [[1. 1.]
 [1. 1.]]


In [9]:
#6. Identity matrices.
c_torch = torch.eye(2)
c_numpy = np.identity(2)

print(c_torch)
print(f'\n {c_numpy}')

tensor([[1., 0.],
        [0., 1.]])

 [[1. 0.]
 [0. 1.]]


In [10]:
#7. Pytorch to numpy and vice versa.
d_torch = torch.from_numpy(c_numpy)
d = c_torch.numpy()

print(d_torch)
print(f'\n {c}')

tensor([[1., 0.],
        [0., 1.]], dtype=torch.float64)

 [[-1.29258469  3.38416106]
 [ 0.52315391 -1.96897259]]


## _2. Forward ⏩ proparagation._ 
#### Perform operations given in the computational graph below.👇
***

![alt text](graph_exercise.jpg 'calculation_graph')

In [11]:
#Initialize tensors x, y and z.
x = torch.rand((1000, 1000))
y = torch.rand((1000, 1000))
z = torch.rand((1000, 1000))

#Multiply x with y.
q = torch.matmul(x, y)

#Multiply element-wise z with q.
f = z * q

mean_f = torch.mean(f)
print(mean_f)

tensor(124.9481)


## _3. Backpropagation by auto-differentiation._

In [12]:
x = torch.tensor(-3., requires_grad = True)
y = torch.tensor(5., requires_grad = True)
z = torch.tensor(-2., requires_grad = True)

q = x + y
f = q * z

# Compute the derivatives
f.backward()

print(f'Gradient of z is: {z.grad}')
print(f'Gradient of y is: {y.grad}')
print(f'Gradient of x is: {x.grad}')

Gradient of z is: 2.0
Gradient of y is: -2.0
Gradient of x is: -2.0


## 4. Fully connencted neural nets.

In [14]:
input_layer = torch.rand(10)

w1 = torch.rand(10, 20)
w2 = torch.rand(20, 20)
w3 = torch.rand(20, 4)

h1 = torch.matmul(input_layer, w1)
h2 = torch.matmul(h1, w2)

output_layer = torch.matmul(h2, w3)
print(output_layer)

tensor([335.3644, 275.4128, 298.5652, 291.5167])


In [15]:
#Building a nn in an object-oriented fashion.
import torch.nn as nn

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(10, 20) #Fully connected neurons.
        self.fc2 = nn.Linear(20, 20)
        self.output = nn.Linear(20, 4)
        
    def forward(self, x):
        x = self.fc1(x)
        x = self.fc2(x)
        x = self.output(x)
        return x

In [16]:
input_layer = torch.rand(10)
net = Net()

result = net(input_layer)
result

tensor([-0.0886, -0.0558,  0.1110, -0.6304], grad_fn=<AddBackward0>)