## Pooling is performed for 2 reasons:
### 1. Making computation more effective as smaller feature maps are easier to deal with.
### 2. Making the learning invariant to translations: making the network robust to shifting or movements of images.

*** 
### The 2 types of pooling operators are 
#### 1. MaxPooling. It takes the `maximum value` of a slice of an input.
#### 2. AveragePoolng. It takes the `average value` of a slice of an input.

In [1]:
import torch
import torch.nn
import torch.nn.functional as F

## 1. Max-pooling in Pytorch.

### OOP style.

In [4]:
inputs = torch.Tensor([[[[3, 1, 3, 5], [6, 0, 7, 9],
                      [3, 2, 1, 4], [0, 2, 4, 3]]]])

max_pooling = torch.nn.MaxPool2d(2)

output_feature = max_pooling(inputs)

print(inputs)
print(output_feature)

tensor([[[[3., 1., 3., 5.],
          [6., 0., 7., 9.],
          [3., 2., 1., 4.],
          [0., 2., 4., 3.]]]])
tensor([[[[6., 9.],
          [3., 4.]]]])


### Functional style.

In [5]:
inputs = torch.Tensor([[[[3, 1, 3, 5], [6, 0, 7, 9],
                      [3, 2, 1, 4], [0, 2, 4, 3]]]])

output_feature_F = F.max_pool2d(inputs, 2)
print(output_feature_F)

tensor([[[[6., 9.],
          [3., 4.]]]])


## 2. Average pooling.

In [6]:
# OOP.
inputs = torch.Tensor([[[[3, 1, 3, 5], [6, 0, 7, 9],
                      [3, 2, 1, 4], [0, 2, 4, 3]]]])

avg_pooling = torch.nn.AvgPool2d(2)
output_feature = avg_pooling(inputs)
print(output_feature)

tensor([[[[2.5000, 6.0000],
          [1.7500, 3.0000]]]])


In [7]:
#Functional style.
inputs = torch.Tensor([[[[3, 1, 3, 5], [6, 0, 7, 9],
                      [3, 2, 1, 4], [0, 2, 4, 3]]]])

output_feature_F = F.avg_pool2d(inputs, 2)
print(output_feature_F)

tensor([[[[2.5000, 6.0000],
          [1.7500, 3.0000]]]])
